<?php get_header(); $u=get_template_directory_uri(); $me=wp_get_current_user(); $initial=$me->exists()?strtoupper(substr($me->display_name?:$me->user_login,0,1)):'U'; ?>
<div class="lc-home">
<header class="lc-header"><a class="lc-brand" href="<?php echo esc_url(home_url('/')); ?>"><span><img src="<?php echo esc_url($u.'/assets/images/brand/le-cercle-logo.png'); ?>" alt=""></span><b>Le Cercle</b></a><nav><a class="active" href="<?php echo esc_url(home_url('/')); ?>">Accueil</a><a href="<?php echo esc_url(home_url('/forum')); ?>">Forum</a><a href="<?php echo esc_url(home_url('/artistes')); ?>">Artistes</a><a href="<?php echo esc_url(home_url('/playlists')); ?>">Playlists</a><a href="<?php echo esc_url(home_url('/evenements')); ?>">Événements</a></nav><div class="lc-tools"><label>⌕ <input class="lc-home-search" placeholder="Rechercher..."></label><a href="<?php echo esc_url(is_user_logged_in()?home_url('/profil'):home_url('/login')); ?>"><?php echo esc_html($initial); ?></a></div></header>
<main class="lc-grid">
<aside class="lc-panel lc-filters"><header><h2>Filtres</h2><small>Affiner le contenu</small></header><nav><button class="active" data-feed-filter="all">▦ Tous les posts</button><button data-feed-filter="freestyle">♩ Freestyles</button><button data-feed-filter="beats">♫ Beats</button><button data-feed-filter="concerts">◫ Concerts</button><button type="button" class="lc-filter-deals" onclick="window.location.href='<?php echo esc_url(home_url('/bons-plans')); ?>'">◇ Bons plans</button><button data-feed-filter="favorites">☆ Favoris</button></nav></aside>
<section class="lc-feed"><header><h1>Fil d’actualité</h1><p class="lc-feed-status" aria-live="polite">Découvrez les dernières publications de la communauté</p></header><div class="lc-compose" data-member-name="<?php echo esc_attr($me->exists() ? ($me->display_name ?: $me->user_login) : 'Membre Le Cercle'); ?>" data-member-initial="<?php echo esc_attr($initial); ?>"><i><?php echo esc_html($initial); ?></i><input maxlength="280" placeholder="Quoi de neuf dans le Cercle ?" aria-label="Votre publication"><button type="button" class="lc-compose-submit">Publier</button></div>
<?php $posts=[['M','MC Lyricist','Freestyle','@mclyricist · 2h','Nouveau freestyle en studio ! Le flow est de retour 🔥 Restez connectés pour la sortie prochaine du morceau complet. #LeCercle #RapFrançais','home-post-1.png',342,56,'freestyle'],['D','DJ Beatmaker','Beats','@djbeatmaker · 5h','Session de production nocturne... Quand la créativité frappe à 3h du matin. Nouveau beat boom bap disponible bientôt sur le site !','home-post-2.png',218,31,'beats'],['B','Booba Live','Concerts','@booba · 1j','Concert Live Booba : rendez-vous à Paris le 15 mars 2027. Qui sera là pour la soirée ?','../events/booba-live.jpg',516,84,'concerts']]; foreach($posts as $post_index=>$p): ?>
<article class="lc-post" data-post="demo-<?php echo esc_attr($post_index+1); ?>" data-feed-type="<?php echo esc_attr($p[8]); ?>" data-search="<?php echo esc_attr(strtolower($p[1].' '.$p[2].' '.$p[4])); ?>"><header><i><?php echo esc_html($p[0]); ?></i><div><h2><?php echo esc_html($p[1]); ?> <em><?php echo esc_html($p[2]); ?></em></h2><small><?php echo esc_html($p[3]); ?></small></div><b>•••</b></header><p><?php echo esc_html($p[4]); ?></p><img src="<?php echo esc_url($u.'/assets/images/figma/'.$p[5]); ?>" alt=""><footer class="lc-actions"><button class="lc-like" data-count="<?php echo esc_attr($p[6]); ?>" aria-pressed="false"><span>♡</span> <b><?php echo esc_html($p[6]); ?></b></button><span><button class="lc-comment" aria-expanded="false">◯ <?php echo esc_html($p[7]); ?></button><button class="lc-share" aria-label="Partager">⌯</button><button class="lc-save" aria-label="Enregistrer dans les favoris" aria-pressed="false"><img src="<?php echo esc_url($u.'/assets/icons/figma/bookmark.svg'); ?>" alt=""></button></span></footer><div class="lc-comments" hidden><input placeholder="Écrire un commentaire..."><button>Publier</button></div></article><?php endforeach; ?>
<p class="lc-feed-empty" hidden>Aucune publication ne correspond à ta recherche.</p>
</section>
<aside class="lc-side"><section class="lc-panel lc-list"><h2>↗ Tendances actuelles</h2><a>Top Albums Rap Français 2025<small>par RapCritic</small></a><a>Résultats Battle Freestyle<small>par BattleHub</small></a><a>Meilleurs Beats Boom Bap<small>par BeatCollective</small></a></section><section class="lc-panel lc-events"><h2>▣ Événements à venir</h2><article><time>15<small>MAR</small></time><b>Concert Live Booba<small>⌖ Paris</small></b></article><article><time>22<small>MAR</small></time><b>Soirée Cypher Freestyle<small>⌖ Lyon</small></b></article></section></aside>
</main></div><?php get_footer(); ?>
