<?php
/* Template Name: Événements */
get_header();
$u = get_template_directory_uri();
$me = wp_get_current_user();
$initial = $me->exists() ? strtoupper(substr($me->display_name ?: $me->user_login, 0, 1)) : 'U';
$events = array(
    array('15', 'MAR', 'Concert', 'Concert Live Booba', 'Accor Arena · Paris', '20:00', 'Une date XXL, des classiques et une énergie live.', 'concert'),
    array('22', 'MAR', 'Freestyle', 'Soirée Cypher Freestyle', 'Le Transbordeur · Lyon', '19:30', 'Scène ouverte, MCs et invités surprise toute la soirée.', 'freestyle'),
    array('05', 'AVR', 'Rencontre', 'Open Mic Le Cercle', 'LaVallée · Bruxelles', '18:30', 'Une scène pour poser, écouter et rencontrer la communauté.', 'openmic'),
    array('12', 'AVR', 'Session', 'Rap & RnB Session', 'Le Trabendo · Paris', '20:30', 'Un live plus doux, entre voix émergentes et invités.', 'rnb'),
);
?>
<style>
/* Photo Booba — Wikimedia Commons, Arnaud Scherer (CC BY-SA 4.0). */
.lc-events-feature-art--booba{background-image:linear-gradient(180deg,rgba(10,10,10,.04) 22%,rgba(10,10,10,.72) 100%),url("<?php echo esc_url($u.'/assets/images/events/booba-live.jpg'); ?>");background-position:center 34%;background-size:cover}.lc-events-feature-art--booba:before,.lc-events-feature-art--booba:after{border-color:rgba(255,199,0,.32)}.lc-events-feature-art--booba small,.lc-events-feature-art--booba span{color:rgba(255,255,255,.74)}
.lc-event-dialog{width:min(500px,calc(100% - 32px));margin:auto;padding:0;border:1px solid #3a3a3a;border-radius:20px;background:#181818;color:#f6f6f6;box-shadow:0 28px 110px rgba(0,0,0,.78)}.lc-event-dialog::backdrop{background:rgba(0,0,0,.78);backdrop-filter:blur(7px)}.lc-event-dialog form{margin:0}.lc-event-dialog-head{display:flex;align-items:center;justify-content:space-between;padding:20px 23px;border-bottom:1px solid #303030}.lc-event-dialog-head span{color:#ffc700;font-size:11px;font-weight:900;letter-spacing:.12em}.lc-event-dialog-close{width:34px;height:34px;border:1px solid #393939;border-radius:50%;background:#222;color:#b7b7b7;font-size:23px;line-height:1;cursor:pointer}.lc-event-dialog-body{padding:28px 23px}.lc-event-dialog-body h2{margin:0 0 10px;font:900 29px/.98 Montserrat,sans-serif;letter-spacing:-.05em}.lc-event-dialog-meta{margin:0;color:#ffc700;font-size:13px;font-weight:800}.lc-event-dialog-description{margin:15px 0 0;color:#b7b7b7;font-size:14px;line-height:1.55}.lc-event-dialog-note{display:none;margin:17px 0 0;padding:12px;border:1px solid rgba(118,229,175,.32);border-radius:11px;background:rgba(118,229,175,.1);color:#8cf0bb;font-size:13px;font-weight:700}.lc-event-dialog.is-confirmed .lc-event-dialog-note{display:block}.lc-event-dialog-footer{display:flex;justify-content:flex-end;gap:10px;padding:17px 23px;border-top:1px solid #303030}.lc-event-dialog-footer button{padding:11px 15px;border-radius:11px;font-size:13px;font-weight:900;cursor:pointer}.lc-event-dialog-cancel{border:1px solid #3a3a3a;background:#202020;color:#aaa}.lc-event-dialog-confirm{border:0;background:#ffc700;color:#141414}.lc-event-card{cursor:pointer}.lc-event-card:focus-visible{outline:2px solid #ffc700;outline-offset:3px}@media(max-width:480px){.lc-event-dialog-body{padding:24px 19px}.lc-event-dialog-footer{padding:15px 19px}.lc-event-dialog-footer button{padding:10px 12px}}
</style>
<div class="lc-home lc-events-page">
  <header class="lc-header"><a class="lc-brand" href="<?php echo esc_url(home_url('/')); ?>"><span><img src="<?php echo esc_url($u.'/assets/images/brand/le-cercle-logo.png'); ?>" alt=""></span><b>Le Cercle</b></a><nav><a href="<?php echo esc_url(home_url('/')); ?>">Accueil</a><a href="<?php echo esc_url(home_url('/forum')); ?>">Forum</a><a href="<?php echo esc_url(home_url('/artistes')); ?>">Artistes</a><a href="<?php echo esc_url(home_url('/playlists')); ?>">Playlists</a><a class="active" href="<?php echo esc_url(home_url('/evenements')); ?>">Événements</a></nav><div class="lc-tools"><label>⌕ <input class="lc-events-search" placeholder="Rechercher..."></label><a href="<?php echo esc_url(is_user_logged_in()?home_url('/profil'):home_url('/login')); ?>"><?php echo esc_html($initial); ?></a></div></header>
  <main class="lc-events">
    <section class="lc-events-hero"><div><span>AGENDA LE CERCLE</span><h1>Les rendez-vous qui font vibrer la communauté.</h1><p>Concerts, freestyles et rencontres : retrouve les moments à vivre avec celles et ceux qui font le rap d’aujourd’hui.</p></div><p class="lc-events-count"><b>04</b><span>dates<br>à venir</span></p></section>
    <section class="lc-events-feature"><div class="lc-events-feature-copy"><span>À NE PAS MANQUER</span><p class="lc-events-feature-date"><b>15</b> <span>MARS<br>2027</span></p><h2>Concert Live<br>Booba</h2><p>Accor Arena · Paris · 20:00</p><button type="button" class="lc-event-reserve" data-event="Concert Live Booba">Réserver ma place <b>→</b></button></div><div class="lc-events-feature-art lc-events-feature-art--booba" role="img" aria-label="Booba en concert"><small>LE CERCLE</small><strong>LIVE</strong><span>PARIS · 15.03</span></div></section>
    <section class="lc-events-list"><header><div><h2>Prochainement</h2><p>Choisis ton prochain rendez-vous.</p></div><span><b>4</b> événements</span></header><div class="lc-events-filters"><button class="is-active" type="button" data-event-filter="all">Tout voir</button><button type="button" data-event-filter="concert">Concerts</button><button type="button" data-event-filter="freestyle">Freestyles</button><button type="button" data-event-filter="openmic">Open mic</button></div><div class="lc-event-grid"><?php foreach ($events as $event) : ?><article class="lc-event-card" tabindex="0" data-kind="<?php echo esc_attr($event[7]); ?>" data-search="<?php echo esc_attr(strtolower(implode(' ', $event))); ?>"><div class="lc-event-date"><b><?php echo esc_html($event[0]); ?></b><span><?php echo esc_html($event[1]); ?></span></div><div class="lc-event-details"><em><?php echo esc_html($event[2]); ?></em><h3><?php echo esc_html($event[3]); ?></h3><p><?php echo esc_html($event[4]); ?> · <?php echo esc_html($event[5]); ?></p><small><?php echo esc_html($event[6]); ?></small></div><button class="lc-event-reserve" type="button" data-event="<?php echo esc_attr($event[3]); ?>">Réserver <b>→</b></button></article><?php endforeach; ?></div></section>
    <dialog class="lc-event-dialog"><form method="dialog"><header class="lc-event-dialog-head"><span>RÉSERVATION</span><button type="submit" class="lc-event-dialog-close" aria-label="Fermer">×</button></header><div class="lc-event-dialog-body"><h2></h2><p class="lc-event-dialog-meta"></p><p class="lc-event-dialog-description"></p><p class="lc-event-dialog-note">✓ Ta place est réservée. On te retrouve là-bas.</p></div><footer class="lc-event-dialog-footer"><button type="submit" class="lc-event-dialog-cancel">Annuler</button><button type="button" class="lc-event-dialog-confirm">Réserver ma place</button></footer></form></dialog>
  </main>
</div>
<?php get_footer(); ?>
